### ISSUE TITLE
after install, no yaml support

### ISSUE THREAD

**Issue by chewmanfoo** [imeyer/ruby-1.9.3-rpm#7]
I see this error message when using ruby built with this spec file:

It seems your ruby installation is missing psych (for YAML output).

This is on CentOS 5.6

What do I need to do about this?

**Comment by imeyer** [comment]
Let me take a look at this tomorrow at work and see if I can get this sorted out for you. At a glance, it looks like it should just work as it depends on `libyaml` and `libyaml-devel`. Thanks for reporting this.

**Comment by imeyer** [comment]
In my 1.9.3 install this is what I see

```
xxxxx /Users/imeyer: irb -ryaml
1.9.3p194 :001 > YAML::ENGINE
 => #<YAML::EngineManager:0x007fe6d3862b78 @yamler="psych">
```

Can you show me the output of the above command? Thanks!

**Comment by imeyer** [comment]
Ah I did find that it was not enabled on CentOS 5.8 but compiling `p327` works

```
/home/imeyer/rpmbuild/SPECS: irb -ryaml
irb(main):001:0> YAML::ENGINE
=> #<YAML::EngineManager:0x0000000c9bbb88 @yamler="psych">
/home/imeyer/rpmbuild/SPECS: cat /etc/redhat-release 
CentOS release 5.8 (Final)
```
